<a href="https://colab.research.google.com/github/enesergen/TensorflowFundamentalCourseWithDaniel/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
#tf.constant  ile tensor oluşturma
scaler=tf.constant(6)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [3]:
scaler.ndim#tensorun boyutunu veriri ndim=number of dimension sanırım rank da diebiliriz

0

In [4]:
#vector oluşturma
vector=tf.constant([12,6])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  6], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#matrix oluşturma
matrix=tf.constant([[2,6],[3,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 6],
       [3, 5]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#başka bir matrix oluşturma
another_matrix=tf.constant([[10.,7.],
                            [5.,3.],
                            [2.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 5.,  3.],
       [ 2.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor=tf.constant([
    [
        [1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]
                                               ]
                    ]
                   )
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

#Yukarıda ne öğrendik:
* Scaler:0 boyutlu. 
* Vector=1 boyutlu.
* matrix=2 boyutlu
* tensor=n boyutlu olabilir tamamen oluşturmaya göre boyut sayısını siz belirleyebiliyoruz.



In [12]:
#tf.variable ile tensor oluşturma
changeable_tesnor=tf.Variable([3,4])#değiştirilebilir tensor yani verdiğimiz değerleri değiştirebiliyoruz
unchangeable_tesnor=tf.constant([3,4])#constant sabit değerli tensor
changeable_tesnor,unchangeable_tesnor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [13]:
#değiştirmeyi deneyelim 
changeable_tesnor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [14]:
changeable_tesnor[0].assign(22)
changeable_tesnor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([22,  4], dtype=int32)>

**Eğer ileride değiştirmek zorunda olacağımız bir tensor ile çalışacaksak tf.Variable() ile oluşturmamız gerekiyor aksi halde tf.constant() ile oluşturursak bunu değiştirmek mümkün olmayacaktır.`**

In [15]:
#random tensor oluşturma
random_tensor1=tf.random.Generator.from_seed(42)
random_tensor1=random_tensor1.normal(shape=(3,2))#normal dağılım kullanarak oluşturuyor 
random_tensor2=tf.random.Generator.from_seed(42)
random_tensor2=random_tensor2.normal(shape=(3,2))
random_tensor1,random_tensor1,random_tensor1==random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

** Öğrenme algoritmasını daha iyi hale getirmek için verisetmizi shuffle karıştırma işlemi yapmamız gerekiyor örnek olarak 15bin verilik ilk verisetinin ilk 10bin tanesi bisiklet sonraki 5bin tanesi araba olsun burada sistemimiz ilk 10bin taneden sadece bisikteli öğrenir onun için kendisini eğitir bunun önüne geçebilmek için shuffle yani karıştırma işlemi yapmamız gerekir**

In [16]:
#tensor için shuffle işlemini yapmak
not_shuffled=tf.constant([
    [1,2,3],[4,5,6],[7,8,9]
])
not_shuffled.ndim

2

In [17]:
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [18]:
tf.random.shuffle(not_shuffled)#random.shuffly first dimension yani (3,3) ün ilk 3 teki boyut üzerinde karışıklık yapar sonraki boyuta karışmaz 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [19]:
tf.random.shuffle(not_shuffled)#random.shuffly first dimension yani (3,3) ün ilk 3 teki boyut üzerinde karışıklık yapar sonraki boyuta karışmaz 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]], dtype=int32)>

In [20]:
tf.random.shuffle(not_shuffled,seed=42)# seed sayısını verdiğimiz zaman ne kadar tekrar çalıştırsakta karıştırma sonucu hep aynı olacaktır
#kodu birden fazlakez çalıştırdım ama sonuç hep aynı sırada çıktı shuffle yaptı ama tekrar tekrar çalıştırdığımda da aynı sonucu elde ettim
#ayrıca 2 tür seed vardır bir global bide operation level seed vardır bunlar biri fonksiyon içinde seed= ile diğeri ise tensor.set_seed() şeklinde kullanılılır 
#bunların farkı sanıyorumki operasyon içindeki sadece o satır için etkili ama global olan bir kere tanımlıyorsunuz ve tüm farklı satırlardaki shuffle için aynı seed değeri kullanılıyor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [21]:
#other tensors
#numpy ones:içinin 1 ile dolu olan tensor oluşturur.
tf.ones([7,10])

<tf.Tensor: shape=(7, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros([3,4])#hepsi 0 olan bir tensor oluşturur

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [23]:
tf.zeros(shape=(3,4))#farklı bir gösterimi

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# * Numpy  array ile tensor arasındaki en büyük fark; tensorlar GPU üzerinde çalışabilirler bu yüzden çok hızlı matematiksel hesaplamaları yapılabilir.

In [24]:
#ayrıca numpy array leri tensor lara dönüştürebiliriz
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32) #numpy array oluşturma 1 ile 20 arasında int32bit tipinde 
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
#numpy array'i tensor a dönüştürme
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [26]:
#ayrıca dönüştürme sırasında shape üzerinde de bir değişklik yapabilriz
B=tf.constant(numpy_A,shape=(2,3,4))#burada 2*3*4=24 numpy array deki eleman sayısını karşılamalıdır.
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Tensor hakkında bilgiler
* Shape
* Rank
* Axis or dimension(boyut)
* Size

In [27]:
#rank 4 olan bir tensor oluşturalım 4 dimension boyutlu demek
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
rank_4_tensor.shape[0],rank_4_tensor.shape[-1]# burada 0 yazan ilk boyut olan 2 yi ; -1 ise son boyut olan 5 i verir.
#yani ilk axis shape[0] ile 2 yi ; ikinci axis shape[1] ile 3 olurdu

(2, 5)

In [30]:
#size öğrenme ve sayısal olarak alma
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [31]:
tf.size(rank_4_tensor).numpy()

120

## Tensorlar indexlenebilirler aynı listeler gibi

In [32]:
#her boyuttaki ilk iki elemanı almak
#önce bir liste örneği
some_list=[1,2,3,4,5]
some_list[:2]

[1, 2]

In [33]:
#şimdi tensor örneği
rank_4_tensor[:2,:2,:2,:2] #şeklinde yapılır her boyut için sırasıyla kaç tanesini almak istediğimizi belirtiriz

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
# tüm boyutlardan 1 tane alıp son boyutu numara yazmadığımız için tamamını aldı
# bu şununla da eşdeğerdir rank_4_tensor[:1,:1,:1] yani yazmasakta olur yine aynı
rank_4_tensor[:1,:1,:1,:],rank_4_tensor[:1,:1,:1]

(<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>)

In [35]:
#bir tensor için boyut değişimi yapmak azaltmak ya da arttırmak
#rank 2 yani 2 boyutlu bir tensor oluşturalım
rank_2_tensor=tf.zeros(shape=(3,5))
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([3, 5]), 2)

In [36]:
#rank2 bir tesnor a bir boyut daha ekleme yani dimension sayısını arttırma
rank_2_another_tensor=tf.constant([[2,4],[7,5]])
rank_3_tesnor=rank_2_another_tensor[...,tf.newaxis]#axis in boyutlar olduğundan bahsetmiştik burada
rank_3_tesnor                                      #(2,2) olan tensor için bir boyut eklendi ve (2,2,1) olmuş oldu

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[7],
        [5]]], dtype=int32)>

In [37]:
rank_3_antoher_tensor=rank_2_another_tensor[tf.newaxis,...]
rank_3_antoher_tensor #yukarıdakinin aksine burada da ilk kısma boyut eklendi axisi nereye ekleyeceğimizi seçebiliyoruz

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 4],
        [7, 5]]], dtype=int32)>

In [38]:
#ya da farklı bir gösterim veya kullanım olarak şu uygulanabilir
rank_3_another_tensor_2=rank_2_another_tensor[:,tf.newaxis,:] # önceki örneklerde olduğu gibi : kullanabiliriz
rank_3_another_tensor_2                                       # bu şekilde aksisin nereye ekleneceğini belirtebiliyoruz 
                                                              # ortaya ekleyebildiğimiz gibi

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 4]],

       [[7, 5]]], dtype=int32)>

In [39]:
#tf.newaxis e alternatif olarak tf.epand_dims() kullanılabilir 
tf.expand_dims(rank_2_another_tensor,axis=-1)# -1'in anlamı son axisden sonra bir aksis ekle sona ekle gibi
                                             # burada 0 1 veya boyut sayımıza kadar değerler vererek araya da ekleme yapabilir ve genişletebiliriz                                            

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[7],
        [5]]], dtype=int32)>

# Tensor Operasyonları tensoru manipule etmek yönetmek
"+" , "-" , "*" , "/"

In [40]:
tensor=tf.constant([[2,5],[3,7]])
tensor+10#burada atama işlemi olmaz tensor değişmez olması için tensor=tensor+10 yapmamız gerekir
tensor,tensor+15
#bu işlemler diğer temel 3 operasyon için de aynı şekilde işler

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 5],
        [3, 7]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[17, 20],
        [18, 22]], dtype=int32)>)

In [41]:
#ayrıca tenserflowun kendi fonksiyonlarını da kullanabiliriz
tf.multiply(tensor,2)
tensor#görüldüğü gibi yine atama işlemi olmadı
#gpu üzerinde büyük tesnor la daha hızlı işlem için kendi fonksiyonlarını kullanmak gerekir

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 7]], dtype=int32)>

***Matrix Çarpımı***

In [42]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[2 5]
 [3 7]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 45],
       [27, 64]], dtype=int32)>

In [43]:
#python @ operatörü ile matrix çarpımı yapılabilir
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 45],
       [27, 64]], dtype=int32)>

In [44]:
#bir tensoru reshape ile yeniden şekillendirebiliriz
Y=tf.constant([[1,2,3],[4,5,6]])# şekilde shape=(2,3) olan bir tensor var
Y 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

## Reshape yeniden şekillendirme (3,2)->(3,2)

In [45]:
tf.reshape(Y,shape=(3,2))#atama işlemi olmadığı için Y değişmedi ama atama ile bu yeni hali alınabilir

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [46]:
tf.transpose(Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [47]:
#matrix çarpımı ayrıca dotproduct iç çarpımı olarak da gösterilebilir
#tek fark bir tanesinin tranpose olması gerektiğidir örnek gösterim:
#tf.tensordot()


In [48]:
D=tf.constant([-7,10])
tf.abs(D)#negatif değerlerin mutlak değerini alır

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [49]:
E=tf.constant(np.random.randint(0,100,size=50))#random 0 10 arasında 50 elemanlı bir tensor oluşturma
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([76, 23, 71, 16, 92, 26, 75, 44, 67, 52, 37, 20, 22, 16, 23, 21, 91,
       96, 21, 51, 16, 51, 17, 36, 72, 28, 31, 68, 80, 14, 14,  0, 21, 70,
        5, 17, 92,  2, 39, 68, 86, 47, 40, 81, 35, 54, 12, 42, 39, 90])>

In [50]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [51]:
#min max minor sum(toplam) mean(ortalama)
tf.reduce_min(E),tf.reduce_max(E),tf.reduce_mean(E),tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=96>,
 <tf.Tensor: shape=(), dtype=int64, numpy=44>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2207>)

In [52]:
import tensorflow_probability as tfp#variant fonksiyonu için import edildi
tfp.stats.variance(E)#varyans bulma

<tf.Tensor: shape=(), dtype=int64, numpy=771>

In [53]:
#standart sapma
tfp.stats.stddev(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.780575>

In [54]:
#positional maximum and minimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [55]:
tf.argmax(F)#burada bize maximum elemanın indexini döner

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [56]:
F[tf.argmax(F)]#burada indexden elemana ulaşabiliriz

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [57]:
#ayrıca max value şu şekilde de bulunabilir
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [58]:
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [59]:
#min bulma
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [60]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing tensor()

In [61]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686, 0.3103881 , 0.7223358 ,
            0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ,
            0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173, 0.9485276 , 0.23752594,
            0.81179297, 0.5263394 , 0.494308  , 0.21612847,
            0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]]]]]], dtype=float32)>

In [62]:
G_squeeze=tf.squeeze(G)
G_squeeze#tüm boyutu 1 olan sayılar sildi

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# one hot encoding tensor

In [63]:
some_list=[0,1,2,3]#red green blue yellow gibi 

In [64]:
tf.one_hot(some_list,depth=4)#dept eleman sayısı yani 4x4 matrix oluşacak

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [65]:
#one hot da 1 veya 0 yerine kendi değerlerimizi yazabiliriz
tf.one_hot(some_list,depth=4,on_value="1 yerine olacak deger",off_value="0 yerine olacak deger")#işin eğlencesi

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'1 yerine olacak deger', b'0 yerine olacak deger',
        b'0 yerine olacak deger', b'0 yerine olacak deger'],
       [b'0 yerine olacak deger', b'1 yerine olacak deger',
        b'0 yerine olacak deger', b'0 yerine olacak deger'],
       [b'0 yerine olacak deger', b'0 yerine olacak deger',
        b'1 yerine olacak deger', b'0 yerine olacak deger'],
       [b'0 yerine olacak deger', b'0 yerine olacak deger',
        b'0 yerine olacak deger', b'1 yerine olacak deger']], dtype=object)>

### Kare,karekök ve logaritma

In [66]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [67]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [68]:
tf.sqrt(tf.cast(H,dtype=tf.float16))#metot float gerektiriyor int ile çalışmıyor

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

# NumPy and Tensor

In [69]:
#numpy ve tensor ilişkilidir numpy array iile tensor oluşturulabilir
J=tf.constant(np.array([2.,3.,4.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [74]:
 #tesnoru np.array dönüştürme
np.array(J), type(np.array(J)) 

(array([2., 3., 4.]), numpy.ndarray)

In [77]:
J.numpy(),type(J.numpy())

(array([2., 3., 4.]), numpy.ndarray)

In [79]:
numpy_J=tf.constant(np.array([3.,5.,10.]))
tensor_J=tf.constant([3.,5.,10.] )

In [82]:
numpy_J.dtype,tensor_J.dtype#farklı tiptelerde float64 float32 gibi  

(tf.float64, tf.float32)